create table if not exists registration_fields (
  id uuid primary key default gen_random_uuid(),
  field_key text not null unique,
  label text not null,
  field_type text not null,
  options jsonb,
  required boolean not null default true,
  position integer not null default 0,
  scope text not null default 'person',
  enabled boolean not null default true,
  help_text text,
  placeholder text,
  locked boolean not null default false,
  section text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint registration_fields_scope_check check (scope in ('person', 'order')),
  constraint registration_fields_type_check check (
    field_type in ('text', 'textarea', 'select', 'checkbox', 'date', 'multiselect', 'number', 'email', 'phone', 'photo')
  )
);

do $$
begin
  if not exists (select 1 from pg_trigger where tgname = 'set_registration_fields_updated_at') then
    create trigger set_registration_fields_updated_at before update on registration_fields
    for each row execute function set_updated_at();
  end if;
end $$;

insert into registration_fields (
  field_key,
  label,
  field_type,
  options,
  required,
  position,
  scope,
  enabled,
  help_text,
  placeholder,
  locked,
  section
) values
  (
    'full_name',
    'Full name',
    'text',
    null,
    true,
    1,
    'person',
    true,
    null,
    'First and last name',
    true,
    'Participant Details'
  ),
  (
    'age',
    'Age',
    'number',
    null,
    true,
    2,
    'person',
    true,
    null,
    'Age',
    false,
    'Participant Details'
  ),
  (
    'relationship',
    'Relationship',
    'text',
    null,
    true,
    3,
    'person',
    true,
    null,
    'Relationship to the family',
    false,
    'Participant Details'
  ),
  (
    'lineage',
    'Lineage',
    'select',
    '[{"label":"Nawai","value":"Nawai"},{"label":"Katherine","value":"Katherine"},{"label":"Amy","value":"Amy"},{"label":"Charles","value":"Charles"},{"label":"Myra","value":"Myra"},{"label":"Winifred","value":"Winifred"},{"label":"Henry","value":"Henry"},{"label":"Royden","value":"Royden"},{"label":"Other / Not listed","value":"Other / Not listed"}]'::jsonb,
    true,
    4,
    'person',
    true,
    null,
    null,
    false,
    'Participant Details'
  ),
  (
    'lineage_other',
    'Lineage details (if other)',
    'text',
    null,
    false,
    5,
    'person',
    true,
    'Required when selecting Other / Not listed.',
    'Share your lineage details',
    false,
    'Participant Details'
  ),
  (
    'attendance_days',
    'Attendance days',
    'multiselect',
    '[{"label":"Friday (July 10)","value":"Friday"},{"label":"Saturday (July 11)","value":"Saturday"},{"label":"Sunday (July 12)","value":"Sunday"}]'::jsonb,
    true,
    6,
    'person',
    true,
    null,
    null,
    false,
    'Participation'
  ),
  (
    'tshirt_size',
    'T-shirt size',
    'select',
    '[{"label":"XS","value":"XS"},{"label":"S","value":"S"},{"label":"M","value":"M"},{"label":"L","value":"L"},{"label":"XL","value":"XL"},{"label":"2XL","value":"2XL"},{"label":"3XL","value":"3XL"},{"label":"4XL","value":"4XL"}]'::jsonb,
    true,
    7,
    'person',
    true,
    null,
    null,
    false,
    'Participation'
  ),
  (
    'tshirt_quantity',
    'T-shirt quantity',
    'number',
    null,
    true,
    8,
    'person',
    true,
    null,
    null,
    false,
    'Participation'
  ),
  (
    'email',
    'Email',
    'email',
    null,
    true,
    9,
    'person',
    true,
    null,
    'name@email.com',
    true,
    'Contact'
  ),
  (
    'phone',
    'Phone',
    'phone',
    null,
    true,
    10,
    'person',
    true,
    null,
    '808-555-1234',
    false,
    'Contact'
  ),
  (
    'address',
    'Mailing address',
    'textarea',
    null,
    true,
    11,
    'person',
    true,
    null,
    'Street, city, zip',
    false,
    'Contact'
  ),
  (
    'same_contact',
    'Use primary contact details',
    'checkbox',
    null,
    false,
    12,
    'person',
    true,
    'Only for additional participants.',
    null,
    false,
    'Contact'
  ),
  (
    'photo_upload',
    'Upload a photo',
    'photo',
    null,
    false,
    13,
    'person',
    true,
    'Optional, but helps us recognize each person in the family photo wall.',
    null,
    false,
    'Who\'s Coming'
  ),
  (
    'show_name',
    'Show name in Who\'s Coming',
    'checkbox',
    null,
    false,
    14,
    'person',
    true,
    null,
    null,
    false,
    'Who\'s Coming'
  ),
  (
    'show_photo',
    'Show photo in Who\'s Coming',
    'checkbox',
    null,
    false,
    15,
    'person',
    true,
    null,
    null,
    false,
    'Who\'s Coming'
  )
on conflict (field_key) do nothing;
